apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
data:
  username: c2VjcmV0LXVzZXI=         # base64 encode 'secret-user'
  password: c2VjcmV0LXBhc3N3b3Jk    # base64 encode 'secret-password'